/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as example from "./example";
export type { example };
export type { Greeter } from "./Greeter";
export * as factories from "./factories";
export type { Greeter } from "./example/Greeter";
export { Greeter__factory } from "./factories/example/Greeter__factory";
